# Crypto Narrative & NLP: offline research pipeline

Run all cells from repository root or notebooks/. Inputs: data/processed/market_daily.parquet and text_daily.parquet. No network calls. If real text is absent, the notebook explicitly uses seeded synthetic fixtures and labels every artifact accordingly. Never mix real prices with synthetic text.

Required environment: project requirements plus matplotlib, nbformat, nbclient and ipykernel. Existing project .venv packages can be reused by the host Jupyter kernel.

In [1]:
from pathlib import Path
import sys, json, hashlib, subprocess
import pandas as pd
import yaml
root = Path.cwd()
if root.name == 'notebooks':
    root = root.parent
assert (root / 'config/config.yaml').is_file(), 'Run from repository root or notebooks/'
sys.path.insert(0, str(root))
# Reuse installed project research packages with the host notebook kernel.
project_packages = root / '.venv' / ('Lib/site-packages' if sys.platform == 'win32' else f'lib/python{sys.version_info.major}.{sys.version_info.minor}/site-packages')
if project_packages.exists():
    sys.path.insert(1, str(project_packages))
from src.models.run import run_analysis
config = yaml.safe_load((root/'config/config.yaml').read_text(encoding='utf-8'))
real = (root/'data/processed/text_daily.parquet').is_file()
if real:
    market = pd.read_parquet(root/'data/processed/market_daily.parquet')
    text = pd.read_parquet(root/'data/processed/text_daily.parquet')
else:
    import importlib.util
    spec = importlib.util.spec_from_file_location('fixture_data', root/'tests/fixtures/make_fixtures.py')
    fixture_data = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(fixture_data)
    market, text = fixture_data.make_fixtures(config)
mode = 'real' if real else 'synthetic'
print(mode.upper(), 'market rows', len(market), 'text rows', len(text))
ucry_path = root/'data/processed/ucry_daily.parquet'
ucry = pd.read_parquet(ucry_path) if real and ucry_path.exists() else None

REAL market rows 6845 text rows 1493

## Recompute all tables and paper figures

Three feature sets: market, market + log(n_docs), market + text. Tuning uses development labels only. Every refit purges horizon plus embargo. GW uses fixed 500-observation windows. Quantile windows cover 500 calendar days and move by 20 days.

In [2]:
output = root/'outputs/tables'/mode
figures = root/'outputs/figures'/mode
tables = run_analysis(market, text, config, output, figures, real=real, ucry=ucry)
print('Written:', output, figures)
metadata = {'result_source': mode, 'config': config, 'refit_days': 30,
            'pipeline_commit': subprocess.check_output(['git','rev-parse','HEAD'], cwd=root, text=True).strip(),
            'input_rows': {'market': len(market), 'text': len(text)}}
(output/'run_metadata.json').write_text(json.dumps(metadata, indent=2)+'\n', encoding='utf-8')

Running econometrics

Running robustness

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(
C:\Users\Dell\crypto-narrative-nlp\src\models\econometrics.py:30: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  fit = sm.OLS(data[target], sm.add_constant(data[features], has_constant='add')).fit(

Running quantiles

Running expanding forecasts

ML: BNB, h=1, target=ret

ML: BNB, h=1, target=rv

ML: BTC, h=1, target=ret

ML: BTC, h=1, target=rv

ML: ETH, h=1, target=ret

ML: ETH, h=1, target=rv

ML: SOL, h=1, target=ret

ML: SOL, h=1, target=rv

ML: XRP, h=1, target=ret

ML: XRP, h=1, target=rv

ML: BNB, h=3, target=ret

ML: BNB, h=3, target=rv

ML: BTC, h=3, target=ret

ML: BTC, h=3, target=rv

ML: ETH, h=3, target=ret

ML: ETH, h=3, target=rv

ML: SOL, h=3, target=ret

ML: SOL, h=3, target=rv

ML: XRP, h=3, target=ret

ML: XRP, h=3, target=rv

ML: BNB, h=7, target=ret

ML: BNB, h=7, target=rv

ML: BTC, h=7, target=ret

ML: BTC, h=7, target=rv

ML: ETH, h=7, target=ret

ML: ETH, h=7, target=rv

ML: SOL, h=7, target=ret

ML: SOL, h=7, target=rv

ML: XRP, h=7, target=ret

ML: XRP, h=7, target=rv

Written: C:\Users\Dell\crypto-narrative-nlp\outputs\tables\real C:\Users\Dell\crypto-narrative-nlp\outputs\figures\real

1988

In [3]:
display(tables['coverage'])
for name in ['regressions','wald','quantiles','granger','oos','gw','mcs','ml_status']:
    print(name, len(tables[name]), 'rows')
    display(tables[name].head(10))
audit = tables['refit_audit']
if not audit.empty:
    assert (audit.train_target_max + pd.to_timedelta(audit.horizon+audit.embargo, unit='D') < audit.origin).all()
print((output/'README.md').read_text(encoding='utf-8'))

,asset,calendar_days,news_days,pct_days_with_news,usable_model_days,finbert_days,pct_days_with_finbert,model_development_days,model_test_days,news_start,news_end,model_start,model_end,configured_start,configured_end
0,BNB,1369,31,2.264427,7,31,2.264427,7,0,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2023-01-02 00:00:00+00:00,2023-01-09 00:00:00+00:00,2023-01-01,2026-09-30
1,BTC,1369,31,2.264427,7,31,2.264427,7,0,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2023-01-02 00:00:00+00:00,2023-01-09 00:00:00+00:00,2023-01-01,2026-09-30
2,ETH,1369,31,2.264427,6,31,2.264427,6,0,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2023-01-03 00:00:00+00:00,2023-01-09 00:00:00+00:00,2023-01-01,2026-09-30
3,SOL,1369,31,2.264427,5,31,2.264427,5,0,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2023-01-03 00:00:00+00:00,2023-01-08 00:00:00+00:00,2023-01-01,2026-09-30
4,XRP,1369,31,2.264427,6,31,2.264427,6,0,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2023-01-02 00:00:00+00:00,2023-01-08 00:00:00+00:00,2023-01-01,2026-09-30

regressions 2547 rows

,asset,horizon,target,sentiment,version,term,coef,se,pvalue,identified,nobs,r2,p_holm,p_bh
0,BNB,1,ret,none,market,const,0.053666,0.106279,0.613591,True,24.0,0.433044,1.000000,0.717527
1,BNB,1,ret,none,market,ret,-0.344301,0.076541,0.000007,True,24.0,0.433044,0.013558,0.000031
2,BNB,1,ret,none,market,rv,3.344181,3.976232,0.400324,True,24.0,0.433044,1.000000,0.529675
3,BNB,1,ret,none,market,logvol,-0.002674,0.005819,0.645832,True,24.0,0.433044,1.000000,0.744348
4,BNB,1,ret,none,market,ret_lag1,0.183455,0.277579,0.508668,True,24.0,0.433044,1.000000,0.629227
5,BNB,1,ret,none,market,ret_lag2,-0.005075,0.102565,0.960534,True,24.0,0.433044,1.000000,0.978463
6,BNB,1,ret,none,market,ret_lag3,0.345830,0.128922,0.007308,True,24.0,0.433044,1.000000,0.018670
7,BNB,1,ret,none,market,ret_lag4,0.244080,0.171068,0.153637,True,24.0,0.433044,1.000000,0.252441
8,BNB,1,ret,none,market,ret_lag5,0.291839,0.067038,0.000013,True,24.0,0.433044,0.026225,0.000058
9,BNB,1,ret,none,market,ret_lag6,-0.562399,0.275368,0.041116,True,24.0,0.433044,1.000000,0.083378

wald 15 rows

,asset,horizon,beta_neg,beta_pos,identified,statistic,pvalue,p_holm,p_bh
0,BNB,1,0.001766,-0.000648,True,139.909922,2.785556e-32,4.178334e-31,4.178334e-31
1,BTC,1,-0.000568,-0.001329,True,0.278612,5.976123e-01,1.000000e+00,6.895526e-01
2,ETH,1,0.001150,0.001216,True,0.018351,8.922445e-01,1.000000e+00,9.324148e-01
3,SOL,1,-0.007586,-0.018026,True,11.838357,5.802301e-04,5.222071e-03,1.243350e-03
4,XRP,1,0.099726,-0.004090,True,26.294809,2.930754e-07,3.223829e-06,8.792261e-07
5,BNB,3,0.001980,0.005930,True,30.227782,3.841669e-08,4.994170e-07,1.920835e-07
6,BTC,3,0.001808,-0.003322,True,29.125586,6.783518e-08,8.140221e-07,2.543819e-07
7,ETH,3,0.000673,0.000087,True,2.933712,8.674782e-02,3.469913e-01,1.084348e-01
8,SOL,3,0.003449,0.003796,True,0.007192,9.324148e-01,1.000000e+00,9.324148e-01
9,XRP,3,-0.003003,-0.001823,True,5.622278,1.773358e-02,9.473572e-02,2.418216e-02

quantiles 18 rows

,asset,horizon,tau,nobs,sample_start,sample_end,target_max,identified,beta_neg,beta_pos,se_neg,se_pos,statistic,pvalue,converged,inference,p_holm,p_bh
0,BTC,1,0.1,31,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-25 00:00:00+00:00,True,0.000169,-0.001131,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN
1,BTC,1,0.5,31,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-25 00:00:00+00:00,True,0.001098,0.001465,3.416818e-09,5.122348e-09,6.606277e+09,3.289011e-41,True,heteroskedastic robust; serial dependence not ...,6.578021e-41,3.946813e-41
2,BTC,1,0.9,31,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-25 00:00:00+00:00,True,-0.001370,-0.004149,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN
3,ETH,1,0.1,30,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-25 00:00:00+00:00,True,-0.000188,-0.000443,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN
4,ETH,1,0.5,30,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-25 00:00:00+00:00,True,0.000795,0.001112,1.629996e-09,1.354978e-09,8.555739e+10,2.090200e-41,True,heteroskedastic robust; serial dependence not ...,6.270600e-41,3.135300e-41
5,ETH,1,0.9,30,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-25 00:00:00+00:00,True,0.002309,0.003480,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN
6,BTC,3,0.1,31,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-27 00:00:00+00:00,True,0.006982,0.001551,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN
7,BTC,3,0.5,31,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-27 00:00:00+00:00,True,0.000777,-0.007449,7.184911e-09,1.077131e-08,7.507914e+11,1.849414e-50,True,heteroskedastic robust; serial dependence not ...,1.109648e-49,1.109648e-49
8,BTC,3,0.9,31,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-27 00:00:00+00:00,True,0.000104,-0.008330,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN
9,ETH,3,0.1,30,2023-01-01 00:00:00+00:00,2024-03-24 00:00:00+00:00,2024-03-27 00:00:00+00:00,True,0.001137,-0.000099,NaN,NaN,NaN,NaN,True,coefficient estimate only; covariance unavaila...,NaN,NaN

granger 10 rows

,asset,outcome,pvalue,nobs,conclusion,p_holm,p_bh
0,BNB,ret,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
1,BNB,rv,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
2,BTC,ret,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
3,BTC,rv,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
4,ETH,ret,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
5,ETH,rv,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
6,SOL,ret,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
7,SOL,rv,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
8,XRP,ret,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN
9,XRP,rv,NaN,9,VAR pending: fewer than 30 contiguous daily ob...,NaN,NaN

oos 0 rows

Empty DataFrame
Columns: [asset, target, horizon, model, version, nobs, rmse, r2_oos_ct]
Index: []

gw 0 rows

Empty DataFrame
Columns: [asset, target, horizon, model, gw, gw_pvalue, nobs, gw_p_holm, gw_p_bh]
Index: []

mcs 0 rows

Empty DataFrame
Columns: [asset, target, horizon, version, model, mcs_pvalue, included, mcs_p_holm, mcs_p_bh]
Index: []

ml_status 30 rows

,asset,target,horizon,status,n_valid,n_test
0,BNB,ret,1,insufficient validation/test coverage,0,0
1,BNB,rv,1,insufficient validation/test coverage,0,0
2,BTC,ret,1,insufficient validation/test coverage,0,0
3,BTC,rv,1,insufficient validation/test coverage,0,0
4,ETH,ret,1,insufficient validation/test coverage,0,0
5,ETH,rv,1,insufficient validation/test coverage,0,0
6,SOL,ret,1,insufficient validation/test coverage,0,0
7,SOL,rv,1,insufficient validation/test coverage,0,0
8,XRP,ret,1,insufficient validation/test coverage,0,0
9,XRP,rv,1,insufficient validation/test coverage,0,0

# REAL (partial corpus; provenance audit required)

Daily forecast horizon is the single outcome at t+h, not a cumulative h-day return.
Missing news/scores remain missing. No interpolation, fabricated labels or split changes.
Rows with identified=False have rank-deficient design: coefficients are not unique and p-values/standard errors are withheld.
Holm/BH uses each unique comparison table as one family. MCS is evaluation, not test-set model selection.

## Actual coverage

- BNB: 31/1369 days with indexed news (2.26%); FinBERT coverage 2.26%; news 2023-01-01 00:00:00+00:00 to 2024-03-24 00:00:00+00:00; usable one-day model origins 2023-01-02 00:00:00+00:00 to 2023-01-09 00:00:00+00:00 (7 rows).
- BTC: 31/1369 days with indexed news (2.26%); FinBERT coverage 2.26%; news 2023-01-01 00:00:00+00:00 to 2024-03-24 00:00:00+00:00; usable one-day model origins 2023-01-02 00:00:00+00:00 to 2023-01-09 00:00:00+00:00 (7 rows).
- ETH: 31/1369 days with indexed news (2.26%); FinBERT coverage 2.26%; news 2023-01-01 00:00:00+00:00 to 2024-03-24 00:00:00+00:00; usable one-day model origins 2023-01-03 00:00:00+00:00 to 2023-01-09 00:00:00+00:00 (6 rows).
- SOL: 31/1369 days with indexed news (2.26%); FinBERT coverage 2.26%; news 2023-01-01 00:00:00+00:00 to 2024-03-24 00:00:00+00:00; usable one-day model origins 2023-01-03 00:00:00+00:00 to 2023-01-08 00:00:00+00:00 (5 rows).
- XRP: 31/1369 days with indexed news (2.26%); FinBERT coverage 2.26%; news 2023-01-01 00:00:00+00:00 to 2024-03-24 00:00:00+00:00; usable one-day model origins 2023-01-02 00:00:00+00:00 to 2023-01-08 00:00:00+00:00 (6 rows).

## Table interpretation

### regressions.csv (2547 rows)

RQ1/RQ3: coefficients measure conditional predictive associations with returns, RV and volume. Compare market, raw attention and text on the same sample; they do not validate sentiment labels or identify causal effects.

### wald.csv (15 rows)

RQ2: rejection means negative and positive sentiment have different conditional RV slopes. It does not prove that negative news causes volatility.

### granger.csv (10 rows)

RQ4: text-to-market significance indicates a predictive lead, while the reverse direction suggests price feedback. Missing/short contiguous samples cannot support this inference.

### stationarity.csv (40 rows)

RQ4: ADF tests a unit-root null and KPSS tests a level-stationarity null. Conflicting outcomes call for specification review; KPSS p-values are lookup-table bounds.

### robustness.csv (1215 rows)

RQ1–RQ3: compare pre/post January 2025 and horizon sensitivity with momentum and raw document count. A break dummy cannot repair changing news coverage.

### robustness_status.csv (2 rows)

Document-weighted and price-excluded sensitivity requires reaggregation from canonical articles. Pending means no economic conclusion from that variant.

### quantiles.csv (18 rows)

RQ2: negative/positive RV slopes at tau 0.1/0.5/0.9 expose tail asymmetry hidden by mean regressions. Reported heteroskedastic-robust p-values do not correct serial dependence.

### rolling_quantiles.csv (18 rows)

RQ2: 500-calendar-day, 20-day-step coefficients show temporal stability. Overlapping windows are dependent and cannot be counted as independent replications.

### quantile_status.csv (15 rows)

Short samples cannot estimate the requested rolling window. An unavailable window provides no evidence of stable tail effects.

### oos.csv (0 rows)

RQ5: positive Campbell–Thompson R² beats the recursive historical mean; lower forecast loss is better. Positive DM/CW favors text; CW with tuned/shrunk nonlinear models remains exploratory.

Unavailable for this input sample; no inference reported.

### forecasts.csv (0 rows)

RQ5: dated paired forecasts let reviewers audit when information and targets were available. They are research predictions, not executable trade instructions.

Unavailable for this input sample; no inference reported.

### strategy.csv (0 rows)

RQ5 economic-value test only: net return includes 10 bps turnover fees and final liquidation. Zero processing latency and omitted extra slippage make it optimistic.

Unavailable for this input sample; no inference reported.

### shap.csv (0 rows)

RQ1/RQ3: development-only SHAP shows inputs used by the validation-selected model. Importance is neither a causal effect nor proof of out-of-sample value.

Unavailable for this input sample; no inference reported.

### tuning.csv (0 rows)

RQ5: validation losses choose model settings before the frozen test pass. Test results never revise these settings.

Unavailable for this input sample; no inference reported.

### refit_audit.csv (0 rows)

RQ5: every recorded refit satisfies max(train_target_date) + horizon + embargo < origin. This conservative purge also applies to fixed-window GW fits.

Unavailable for this input sample; no inference reported.

### ml_status.csv (30 rows)

RQ5: pending or skipped cases lack enough honest validation/test observations or contiguous strategy dates. Missing results are not zero effects.

### gw.csv (0 rows)

RQ5: GW uses fixed 500-observation training windows and origin-known return as its conditioning instrument. Rejection indicates conditional forecast differences, not which model dominates every state.

Unavailable for this input sample; no inference reported.

### mcs.csv (0 rows)

RQ5: the 90% Model Confidence Set retains models not rejected by Tmax block-bootstrap elimination. Membership does not establish superiority or select a trading model on test data.

Unavailable for this input sample; no inference reported.

### ucry_regressions.csv (1215 rows)

RQ3: UCRY-controlled regressions use only dates with released weekly observations, in a separate common sample. Retrospective indices lack vintages and cannot justify live forecast claims.

### ucry_wald.csv (9 rows)

RQ2/RQ3: the asymmetry test conditions on weekly uncertainty where available. Its sample differs from the main table; unavailable post-2024 UCRY is never extrapolated.

### coverage.csv (5 rows)

Coverage distinguishes collected-index news days, FinBERT-scored days and complete model rows; it does not prove absence of real-world news. Sparse dates can select an unrepresentative sample.

## Figures

- sentiment_btc.svg
- quantile_coefficients.svg

## Preliminary RQ1–RQ5

RQ1: predictive coefficients cannot rank sentiment accuracy without independent labeled validation.
RQ2: use mean Wald and tail slopes together; quantile serial inference remains a limitation.
RQ3: compare text against raw attention and momentum before attributing value to narrative composition.
RQ4: Granger establishes predictive direction only, conditional on stationarity and contiguous coverage.
RQ5: paired losses, corrected inference and economic-value tests assess incremental value; never choose models on test.

These are partial real-data associations.
RQ1: BTC h=1 FinBERT return slope -0.0135794, Holm p=1; identified=True; this does not validate sentiment-label accuracy.
RQ3: 137/378 estimable hard-narrative coefficients survive table-family Holm at 5%; evaluate against momentum and raw attention.
RQ2: BTC h=1 mean RV slopes negative=-0.000567643, positive=-0.00132876; equality Holm p=1.
RQ2 tail tau=0.1: negative=0.000168817, positive=-0.00113149; converged=True, serial inference not corrected.
RQ2 tail tau=0.5: negative=0.00109816, positive=0.00146513; converged=True, serial inference not corrected.
RQ2 tail tau=0.9: negative=-0.00137026, positive=-0.00414905; converged=True, serial inference not corrected.
RQ5 pending: no honest validation/test forecast comparison is available for this sample.

## Methods sources

- Clark & West (2007): https://users.ssc.wisc.edu/~cengel/IMF/ClarkWest2007.pdf
- DM-HLN reference arithmetic: https://github.com/johntwk/Diebold-Mariano-Test/blob/master/dm_test.py
- Giacomini & White (2006): https://doi.org/10.1111/j.1468-0262.2006.00718.x
- Hansen, Lunde & Nason (2011): https://www.kevinsheppard.com/files/teaching/mfe/advanced-econometrics/Hansen_Lunde_Nason.pdf

## Interpretation

Read the generated README for coverage and a per-table explanation of RQ1-RQ5. Synthetic findings validate code only. Sentiment accuracy requires human labels. Quantile intervals ignore serial dependence. Clark-West on tuned trees is exploratory. Strategy plots are economic-value tests after 10 bps fees, not investment advice.