# Crypto Narrative & NLP: offline research pipeline

Run all cells from repository root or notebooks/. Inputs: data/processed/market_daily.parquet and text_daily.parquet. No network calls. If real text is absent, the notebook explicitly uses seeded synthetic fixtures and labels every artifact accordingly. Never mix real prices with synthetic text.

Required environment: project requirements plus matplotlib, nbformat, nbclient and ipykernel. Existing project .venv packages can be reused by the host Jupyter kernel.

In [1]:
from pathlib import Path
import sys, json, hashlib, subprocess
import pandas as pd
import yaml
root = Path.cwd()
if root.name == 'notebooks':
    root = root.parent
assert (root / 'config/config.yaml').is_file(), 'Run from repository root or notebooks/'
sys.path.insert(0, str(root))
# Reuse installed project research packages with the host notebook kernel.
project_packages = root / '.venv' / ('Lib/site-packages' if sys.platform == 'win32' else f'lib/python{sys.version_info.major}.{sys.version_info.minor}/site-packages')
if project_packages.exists():
    sys.path.insert(1, str(project_packages))
from src.models.run import run_analysis
config = yaml.safe_load((root/'config/config.yaml').read_text(encoding='utf-8'))
real = (root/'data/processed/text_daily.parquet').is_file()
if real:
    market = pd.read_parquet(root/'data/processed/market_daily.parquet')
    text = pd.read_parquet(root/'data/processed/text_daily.parquet')
else:
    import importlib.util
    spec = importlib.util.spec_from_file_location('fixture_data', root/'tests/fixtures/make_fixtures.py')
    fixture_data = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(fixture_data)
    market, text = fixture_data.make_fixtures(config)
mode = 'real' if real else 'synthetic'
print(mode.upper(), 'market rows', len(market), 'text rows', len(text))
ucry_path = root/'data/processed/ucry_daily.parquet'
ucry = pd.read_parquet(ucry_path) if real and ucry_path.exists() else None

from src.evaluation.hourly_event import hourly_prices
interim = root/'data/interim'
event_inputs = (pd.read_parquet(interim/'documents.parquet'), pd.read_parquet(interim/'doc_scores.parquet'), hourly_prices()) if real and (interim/'documents.parquet').exists() and (interim/'doc_scores.parquet').exists() else None

REAL market rows 6845 text rows 7326

## Recompute all tables and paper figures

Core spec uses only same-day text; market return lags remain available on sparse news dates. Real runs also read cached hourly Binance bars and canonical articles for event tests. Tercile cutoffs use training articles only. Every refit purges horizon plus embargo; no network calls.

In [2]:
output = root/'outputs/tables'/mode
figures = root/'outputs/figures'/mode
tables = run_analysis(market, text, config, output, figures, real=real, ucry=ucry, event_inputs=event_inputs)
print('Written:', output, figures)
inputs = [root/'data/processed/market_daily.parquet', root/'data/processed/text_daily.parquet']
if ucry is not None:
    inputs.append(ucry_path)
if event_inputs is not None:
    inputs += [interim/'documents.parquet', interim/'doc_scores.parquet']
    inputs += sorted((root/'data/raw').glob('*_1h_*.parquet'))
code_paths = [root/'src/models/run.py', root/'src/models/ml.py', root/'src/evaluation/report.py', root/'src/evaluation/hourly_event.py']
metadata = {'result_source': mode, 'config': config, 'refit_days': 30,
            'pipeline_commit': subprocess.check_output(['git','rev-parse','HEAD'], cwd=root, text=True).strip(),
            'sha256': {str(path): hashlib.sha256(path.read_bytes()).hexdigest() for path in inputs},
            'analysis_code_sha256': hashlib.sha256(b''.join(path.read_bytes() for path in code_paths)).hexdigest()}
(output/'run_metadata.json').write_text(json.dumps(metadata, indent=2)+'\n', encoding='utf-8')

Running econometrics

Running robustness

Running quantiles

Running expanding forecasts

ML: BNB, h=1, target=ret

C:\Users\Dell\crypto-narrative-nlp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

ML: BNB, h=1, target=rv

ML: BTC, h=1, target=ret

ML: BTC, h=1, target=rv

ML: ETH, h=1, target=ret

ML: ETH, h=1, target=rv

ML: SOL, h=1, target=ret

ML: SOL, h=1, target=rv

ML: XRP, h=1, target=ret

ML: XRP, h=1, target=rv

ML: BNB, h=3, target=ret

ML: BNB, h=3, target=rv

ML: BTC, h=3, target=ret

ML: BTC, h=3, target=rv

ML: ETH, h=3, target=ret

ML: ETH, h=3, target=rv

ML: SOL, h=3, target=ret

ML: SOL, h=3, target=rv

ML: XRP, h=3, target=ret

ML: XRP, h=3, target=rv

ML: BNB, h=7, target=ret

ML: BNB, h=7, target=rv

ML: BTC, h=7, target=ret

ML: BTC, h=7, target=rv

ML: ETH, h=7, target=ret

ML: ETH, h=7, target=rv

ML: SOL, h=7, target=ret

ML: SOL, h=7, target=rv

ML: XRP, h=7, target=ret

ML: XRP, h=7, target=rv

Running hourly events

Written: C:\Users\Dell\crypto-narrative-nlp\outputs\tables\real C:\Users\Dell\crypto-narrative-nlp\outputs\figures\real

3626

In [3]:
display(tables['coverage'])
for name in ['regressions','wald','quantiles','granger','oos','gw','mcs','ml_status']:
    print(name, len(tables[name]), 'rows')
    display(tables[name].head(10))
audit = tables['refit_audit']
if not audit.empty:
    assert (audit.train_target_max + pd.to_timedelta(audit.horizon+audit.embargo, unit='D') < audit.origin).all()
print((output/'README.md').read_text(encoding='utf-8'))

if real:
    for name in ['event_coverage', 'event_tests', 'event_asymmetry', 'event_timing']:
        print(name, len(tables.get(name, [])), 'rows')
        display(tables.get(name, pd.DataFrame()).head(10))
    print((output/'RESULTS.md').read_text(encoding='utf-8'))

,asset,calendar_days,news_days,pct_days_with_news,asset_news_days,pct_days_with_asset_news,usable_model_days,fallback_model_days,finbert_days,pct_days_with_finbert,model_development_days,model_test_days,model_train_days,model_valid_days,news_start,news_end,model_start,model_end,configured_start,configured_end
0,BNB,1369,1352,98.758218,801,58.509861,866,551,1352,98.758218,677,189,556,121,2023-01-01 00:00:00+00:00,2026-09-30 00:00:00+00:00,2023-01-01 00:00:00+00:00,2026-09-29 00:00:00+00:00,2023-01-01,2026-09-30
1,BTC,1369,1352,98.758218,1351,98.685172,1344,1,1352,98.758218,1072,272,890,182,2023-01-01 00:00:00+00:00,2026-09-30 00:00:00+00:00,2023-01-01 00:00:00+00:00,2026-09-29 00:00:00+00:00,2023-01-01,2026-09-30
2,ETH,1369,1352,98.758218,1321,96.493791,1253,31,1352,98.758218,1011,242,838,173,2023-01-01 00:00:00+00:00,2026-09-30 00:00:00+00:00,2023-01-01 00:00:00+00:00,2026-09-29 00:00:00+00:00,2023-01-01,2026-09-30
3,SOL,1369,1352,98.758218,1212,88.531775,1035,140,1352,98.758218,864,171,716,148,2023-01-01 00:00:00+00:00,2026-09-30 00:00:00+00:00,2023-01-01 00:00:00+00:00,2026-09-29 00:00:00+00:00,2023-01-01,2026-09-30
4,XRP,1369,1352,98.758218,1272,92.914536,1179,79,1352,98.758218,961,218,784,177,2023-01-01 00:00:00+00:00,2026-09-30 00:00:00+00:00,2023-01-01 00:00:00+00:00,2026-09-29 00:00:00+00:00,2023-01-01,2026-09-30

regressions 4950 rows

,asset,horizon,target,sentiment,version,term,coef,se,pvalue,identified,nobs,resid_df,r2,sample_start,sample_end,target_max,p_holm,p_bh
0,BNB,1,ret,none,market,const,0.073651,0.041962,0.079228,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.377942
1,BNB,1,ret,none,market,ret,0.023607,0.042485,0.578449,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.837389
2,BNB,1,ret,none,market,rv,2.211026,1.565042,0.157727,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.519460
3,BNB,1,ret,none,market,logvol,-0.003967,0.002276,0.081289,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.383583
4,BNB,1,ret,none,market,ret_lag1,0.012666,0.041987,0.762913,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.933140
5,BNB,1,ret,none,market,ret_lag2,0.065587,0.055525,0.237511,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.591984
6,BNB,1,ret,none,market,ret_lag3,0.053078,0.037968,0.162124,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.521790
7,BNB,1,ret,none,market,ret_lag4,0.010483,0.039846,0.792484,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.939593
8,BNB,1,ret,none,market,ret_lag5,-0.022777,0.052281,0.663077,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.888276
9,BNB,1,ret,none,market,ret_lag6,0.004018,0.046508,0.931151,True,677.0,666.0,0.026424,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,1.0,0.980264

wald 15 rows

,asset,horizon,beta_neg,beta_pos,identified,nobs,resid_df,sample_start,sample_end,statistic,pvalue,p_holm,p_bh
0,BNB,1,0.000066,-0.000041,True,677.0,654.0,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,0.087437,0.767461,1.000000,0.972125
1,BTC,1,-0.001256,-0.001084,True,1072.0,1049.0,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,0.152152,0.696488,1.000000,0.972125
2,ETH,1,0.000656,0.001390,True,1011.0,988.0,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,3.048916,0.080791,1.000000,0.403955
3,SOL,1,0.000640,0.000039,True,864.0,841.0,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,0.521842,0.470057,1.000000,0.903732
4,XRP,1,0.002330,-0.000829,True,961.0,938.0,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,0.957197,0.327894,1.000000,0.825892
5,BNB,3,-0.000227,-0.000279,True,675.0,652.0,2023-01-01 00:00:00+00:00,2025-12-28 00:00:00+00:00,0.033176,0.855470,1.000000,0.972125
6,BTC,3,0.000534,0.000550,True,1070.0,1047.0,2023-01-01 00:00:00+00:00,2025-12-28 00:00:00+00:00,0.001221,0.972125,1.000000,0.972125
7,ETH,3,-0.001081,-0.000155,True,1009.0,986.0,2023-01-01 00:00:00+00:00,2025-12-28 00:00:00+00:00,3.266904,0.070691,0.989673,0.403955
8,SOL,3,0.004081,0.001022,True,861.0,838.0,2023-01-01 00:00:00+00:00,2025-12-28 00:00:00+00:00,6.497635,0.010802,0.162027,0.162027
9,XRP,3,-0.001920,-0.001989,True,959.0,936.0,2023-01-01 00:00:00+00:00,2025-12-28 00:00:00+00:00,0.008362,0.927141,1.000000,0.972125

quantiles 45 rows

,asset,horizon,tau,nobs,sample_start,sample_end,target_max,identified,beta_neg,beta_pos,se_neg,se_pos,statistic,pvalue,converged,inference,p_holm,p_bh
0,BNB,1,0.1,677,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.000119,-0.000125,0.000125,0.000101,0.003366,0.953756,True,heteroskedastic robust; serial dependence not ...,1.000000,0.970965
1,BNB,1,0.5,677,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.000105,-0.000100,0.000183,0.000156,0.001470,0.969427,True,heteroskedastic robust; serial dependence not ...,1.000000,0.970965
2,BNB,1,0.9,677,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.001060,-0.001370,0.000779,0.000667,0.278785,0.597678,True,heteroskedastic robust; serial dependence not ...,1.000000,0.970965
3,BTC,1,0.1,1072,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.000197,0.000016,0.000211,0.000182,3.298420,0.069632,True,heteroskedastic robust; serial dependence not ...,1.000000,0.346566
4,BTC,1,0.5,1072,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.000409,-0.000111,0.000367,0.000318,2.068756,0.150642,True,heteroskedastic robust; serial dependence not ...,1.000000,0.484208
5,BTC,1,0.9,1072,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.001267,-0.001095,0.001071,0.000917,0.061996,0.803418,True,heteroskedastic robust; serial dependence not ...,1.000000,0.970965
6,ETH,1,0.1,1011,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.000122,0.000118,0.000164,0.000137,3.933095,0.047621,True,heteroskedastic robust; serial dependence not ...,1.000000,0.306137
7,ETH,1,0.5,1011,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,0.000042,0.000346,0.000252,0.000192,2.305456,0.129240,True,heteroskedastic robust; serial dependence not ...,1.000000,0.447370
8,ETH,1,0.9,1011,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,-0.000743,0.000809,0.000734,0.000602,6.456655,0.011206,True,heteroskedastic robust; serial dependence not ...,0.493053,0.185286
9,SOL,1,0.1,864,2023-01-01 00:00:00+00:00,2025-12-30 00:00:00+00:00,2025-12-31 00:00:00+00:00,True,0.000003,0.000126,0.000411,0.000271,0.140668,0.707713,True,heteroskedastic robust; serial dependence not ...,1.000000,0.970965

granger 20 rows

,asset,outcome,causing,caused,lag,statistic,pvalue,conclusion,nobs,sample_start,sample_end,discarded_observations,p_holm,p_bh
0,BNB,ret,sent_finbert,ret,1,7.053393,7.981976e-03,Predictive lead (not structural causality),896,2023-01-01 00:00:00+00:00,2025-06-14 00:00:00+00:00,183,1.197296e-01,2.660659e-02
1,BNB,ret,ret,sent_finbert,1,16.953695,4.005208e-05,Predictive lead (not structural causality),896,2023-01-01 00:00:00+00:00,2025-06-14 00:00:00+00:00,183,6.408333e-04,1.602083e-04
2,BNB,rv,sent_finbert,rv,7,0.937300,4.763168e-01,No predictive lead at 5%,813,2023-03-25 00:00:00+00:00,2025-06-14 00:00:00+00:00,265,1.000000e+00,5.292409e-01
3,BNB,rv,rv,sent_finbert,7,1.058289,3.882173e-01,No predictive lead at 5%,813,2023-03-25 00:00:00+00:00,2025-06-14 00:00:00+00:00,265,1.000000e+00,5.176230e-01
4,BTC,ret,sent_finbert,ret,7,1.711744,1.019356e-01,No predictive lead at 5%,896,2023-01-01 00:00:00+00:00,2025-06-14 00:00:00+00:00,183,1.000000e+00,2.077833e-01
5,BTC,ret,ret,sent_finbert,7,35.320119,2.297582e-46,Predictive lead (not structural causality),896,2023-01-01 00:00:00+00:00,2025-06-14 00:00:00+00:00,183,4.595164e-45,4.595164e-45
6,BTC,rv,sent_finbert,rv,7,0.995293,4.327707e-01,No predictive lead at 5%,813,2023-03-25 00:00:00+00:00,2025-06-14 00:00:00+00:00,265,1.000000e+00,5.292409e-01
7,BTC,rv,rv,sent_finbert,7,1.245424,2.743241e-01,No predictive lead at 5%,813,2023-03-25 00:00:00+00:00,2025-06-14 00:00:00+00:00,265,1.000000e+00,4.220371e-01
8,ETH,ret,sent_finbert,ret,3,0.227048,8.776154e-01,No predictive lead at 5%,896,2023-01-01 00:00:00+00:00,2025-06-14 00:00:00+00:00,183,1.000000e+00,8.776154e-01
9,ETH,ret,ret,sent_finbert,3,27.244542,3.181760e-17,Predictive lead (not structural causality),896,2023-01-01 00:00:00+00:00,2025-06-14 00:00:00+00:00,183,5.992755e-16,2.121173e-16

oos 270 rows

,asset,target,horizon,model,version,nobs,rmse,mae,r2_oos,r2_oos_ct,...,market_cw_p_holm,market_cw_p_bh,dm_p_holm,dm_p_bh,cw_p_holm,cw_p_bh,attention_dm_p_holm,attention_dm_p_bh,attention_cw_p_holm,attention_cw_p_bh
0,BNB,ret,1,EN,market,189,0.023908,0.015920,0.000842,0.000842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BNB,ret,1,EN,attention,189,0.023908,0.015920,0.000842,0.000842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BNB,ret,1,EN,text,189,0.023907,0.015923,0.000932,0.000932,...,1.0,0.432799,1.0,0.770923,1.0,0.432799,1.0,0.770823,1.0,0.456419
3,BNB,ret,1,XGB,market,189,0.023591,0.015851,0.027161,0.027161,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BNB,ret,1,XGB,attention,189,0.023595,0.015857,0.026864,0.026864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,BNB,ret,1,XGB,text,189,0.023706,0.015944,0.017663,0.017663,...,1.0,0.811233,1.0,0.993605,1.0,0.811233,1.0,0.997198,1.0,0.763831
6,BNB,ret,1,LGBM,market,189,0.024117,0.016149,-0.016697,-0.016697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BNB,ret,1,LGBM,attention,189,0.024054,0.016113,-0.011381,-0.011381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,BNB,ret,1,LGBM,text,189,0.024559,0.016807,-0.054318,-0.054318,...,1.0,0.590330,1.0,0.837519,1.0,0.590330,1.0,0.915314,1.0,0.618463
9,BNB,rv,1,EN,market,189,0.000511,0.000325,0.496431,0.496431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

gw 90 rows

,asset,target,horizon,model,window,nobs,sample_start,sample_end,gw,gw_pvalue,gw_df,gw_p_holm,gw_p_bh
0,BNB,ret,1,EN,500,16,2026-08-09 00:00:00+00:00,2026-08-24 00:00:00+00:00,2.485324,0.288615,2,1.0,0.463845
1,BNB,ret,1,XGB,500,16,2026-08-09 00:00:00+00:00,2026-08-24 00:00:00+00:00,3.452224,0.177975,2,1.0,0.400444
2,BNB,ret,1,LGBM,500,16,2026-08-09 00:00:00+00:00,2026-08-24 00:00:00+00:00,0.544563,0.761640,2,1.0,0.825875
3,BNB,rv,1,EN,500,16,2026-08-09 00:00:00+00:00,2026-08-24 00:00:00+00:00,2.703220,0.258823,2,1.0,0.456747
4,BNB,rv,1,XGB,500,16,2026-08-09 00:00:00+00:00,2026-08-24 00:00:00+00:00,4.141184,0.126111,2,1.0,0.312067
5,BNB,rv,1,LGBM,500,16,2026-08-09 00:00:00+00:00,2026-08-24 00:00:00+00:00,1.515784,0.468653,2,1.0,0.594068
6,BTC,ret,1,EN,500,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,0.274396,0.871798,2,1.0,0.903208
7,BTC,ret,1,XGB,500,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,5.589420,0.061133,2,1.0,0.239483
8,BTC,ret,1,LGBM,500,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,7.114638,0.028515,2,1.0,0.160398
9,BTC,rv,1,EN,500,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,2.585844,0.274468,2,1.0,0.463845

mcs 108 rows

,asset,target,horizon,version,nobs,sample_start,sample_end,model,mcs_pvalue,included,alpha,bootstrap,block_length,seed,mcs_p_holm,mcs_p_bh
0,BTC,ret,1,attention,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,EN,1.000,True,0.1,999,10,42,1.0,1.0
1,BTC,ret,1,attention,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,LGBM,0.475,True,0.1,999,10,42,1.0,1.0
2,BTC,ret,1,attention,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,XGB,0.475,True,0.1,999,10,42,1.0,1.0
3,BTC,ret,1,market,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,EN,1.000,True,0.1,999,10,42,1.0,1.0
4,BTC,ret,1,market,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,LGBM,0.608,True,0.1,999,10,42,1.0,1.0
5,BTC,ret,1,market,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,XGB,0.608,True,0.1,999,10,42,1.0,1.0
6,BTC,ret,1,text,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,EN,1.000,True,0.1,999,10,42,1.0,1.0
7,BTC,ret,1,text,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,LGBM,0.595,True,0.1,999,10,42,1.0,1.0
8,BTC,ret,1,text,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,XGB,0.245,True,0.1,999,10,42,1.0,1.0
9,BTC,ret,3,attention,235,2025-12-31 00:00:00+00:00,2026-08-22 00:00:00+00:00,EN,1.000,True,0.1,999,10,42,1.0,1.0

ml_status 75 rows

,asset,target,horizon,status,n_train,n_valid,n_test,valid_start,valid_end,test_start,test_end
0,BNB,ret,1,coverage,556.0,121.0,189.0,2025-07-02 00:00:00+00:00,2025-12-30 00:00:00+00:00,2026-01-02 00:00:00+00:00,2026-09-29 00:00:00+00:00
1,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
2,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
3,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
4,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
5,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
6,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
7,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
8,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT
9,BNB,ret,1,strategy skipped: calendar gaps,NaN,NaN,NaN,NaT,NaT,NaT,NaT

# REAL (partial corpus; provenance audit required)

Daily forecast horizon is the single outcome at t+h, not a cumulative h-day return.
Missing news/scores remain missing. No interpolation, fabricated labels or split changes.
Rows with identified=False have rank-deficient design: coefficients are not unique and p-values/standard errors are withheld.
Holm/BH uses each unique comparison table as one family. MCS is evaluation, not test-set model selection.

## Actual coverage

- BNB: 1352/1369 corpus news days (98.76%); 801 asset-tagged news days (58.51%); 551 model origins use corpus fallback; FinBERT panel coverage 98.76%; news 2023-01-01 00:00:00+00:00 to 2026-09-30 00:00:00+00:00; usable one-day model origins 2023-01-01 00:00:00+00:00 to 2026-09-29 00:00:00+00:00 (866 rows); train/valid/test=556/121/189.
- BTC: 1352/1369 corpus news days (98.76%); 1351 asset-tagged news days (98.69%); 1 model origins use corpus fallback; FinBERT panel coverage 98.76%; news 2023-01-01 00:00:00+00:00 to 2026-09-30 00:00:00+00:00; usable one-day model origins 2023-01-01 00:00:00+00:00 to 2026-09-29 00:00:00+00:00 (1344 rows); train/valid/test=890/182/272.
- ETH: 1352/1369 corpus news days (98.76%); 1321 asset-tagged news days (96.49%); 31 model origins use corpus fallback; FinBERT panel coverage 98.76%; news 2023-01-01 00:00:00+00:00 to 2026-09-30 00:00:00+00:00; usable one-day model origins 2023-01-01 00:00:00+00:00 to 2026-09-29 00:00:00+00:00 (1253 rows); train/valid/test=838/173/242.
- SOL: 1352/1369 corpus news days (98.76%); 1212 asset-tagged news days (88.53%); 140 model origins use corpus fallback; FinBERT panel coverage 98.76%; news 2023-01-01 00:00:00+00:00 to 2026-09-30 00:00:00+00:00; usable one-day model origins 2023-01-01 00:00:00+00:00 to 2026-09-29 00:00:00+00:00 (1035 rows); train/valid/test=716/148/171.
- XRP: 1352/1369 corpus news days (98.76%); 1272 asset-tagged news days (92.91%); 79 model origins use corpus fallback; FinBERT panel coverage 98.76%; news 2023-01-01 00:00:00+00:00 to 2026-09-30 00:00:00+00:00; usable one-day model origins 2023-01-01 00:00:00+00:00 to 2026-09-29 00:00:00+00:00 (1179 rows); train/valid/test=784/177/218.

## Table interpretation

### regressions.csv (4950 rows)

RQ1/RQ3: coefficients measure conditional predictive associations with returns, RV and volume. Compare market, raw attention and text on the same sample; they do not validate sentiment labels or identify causal effects.

### wald.csv (15 rows)

RQ2: rejection means negative and positive sentiment have different conditional RV slopes. It does not prove that negative news causes volatility.

### granger.csv (20 rows)

RQ4: text-to-market significance indicates a predictive lead, while the reverse direction suggests price feedback. Missing/short contiguous samples cannot support this inference.

### stationarity.csv (50 rows)

RQ4: ADF tests a unit-root null and KPSS tests a level-stationarity null. Conflicting outcomes call for specification review; KPSS p-values are lookup-table bounds.

### robustness.csv (1800 rows)

RQ1–RQ3: compare pre/post January 2025 and horizon sensitivity with momentum and raw document count. A break dummy cannot repair changing news coverage.

### robustness_status.csv (2 rows)

Document-weighted and price-excluded sensitivity requires reaggregation from canonical articles. Pending means no economic conclusion from that variant.

### quantiles.csv (45 rows)

RQ2: negative/positive RV slopes at tau 0.1/0.5/0.9 expose tail asymmetry hidden by mean regressions. Reported heteroskedastic-robust p-values do not correct serial dependence.

### rolling_quantiles.csv (1350 rows)

RQ2: 500-calendar-day, 20-day-step coefficients show temporal stability. Overlapping windows are dependent and cannot be counted as independent replications.

### quantile_status.csv (15 rows)

Short samples cannot estimate the requested rolling window. An unavailable window provides no evidence of stable tail effects.

### oos.csv (270 rows)

RQ5: positive Campbell–Thompson R² beats the recursive historical mean; lower forecast loss is better. Positive DM/CW favors text; CW with tuned/shrunk nonlinear models remains exploratory.

### forecasts.csv (58284 rows)

RQ5: dated paired forecasts let reviewers audit when information and targets were available. They are research predictions, not executable trade instructions.

### strategy.csv (0 rows)

RQ5 economic-value test only: net return includes 10 bps turnover fees and final liquidation. Zero processing latency and omitted extra slippage make it optimistic.

Unavailable for this input sample; no inference reported.

### shap.csv (1050 rows)

RQ1/RQ3: development-only SHAP shows inputs used by the validation-selected model. Importance is neither a causal effect nor proof of out-of-sample value.

### tuning.csv (540 rows)

RQ5: validation losses choose model settings before the frozen test pass. Test results never revise these settings.

### refit_audit.csv (7518 rows)

RQ5: every recorded refit satisfies max(train_target_date) + horizon + embargo < origin. This conservative purge also applies to fixed-window GW fits.

### ml_status.csv (75 rows)

RQ5: pending or skipped cases lack enough honest validation/test observations or contiguous strategy dates. Missing results are not zero effects.

### gw.csv (90 rows)

RQ5: GW uses fixed 500-observation training windows and origin-known return as its conditioning instrument. Rejection indicates conditional forecast differences, not which model dominates every state.

### mcs.csv (108 rows)

RQ5: the 90% Model Confidence Set retains models not rejected by Tmax block-bootstrap elimination. Membership does not establish superiority or select a trading model on test data.

### ucry_regressions.csv (5400 rows)

RQ3: UCRY-controlled regressions use only dates with released weekly observations, in a separate common sample. Retrospective indices lack vintages and cannot justify live forecast claims.

### ucry_wald.csv (15 rows)

RQ2/RQ3: the asymmetry test conditions on weekly uncertainty where available. Its sample differs from the main table; unavailable post-2024 UCRY is never extrapolated.

### event_observations.csv (150160 rows)

Each row is a canonical English article and tagged asset, or BTC for untagged market news. CAR uses an hourly BTC market model for altcoins and a past-hour mean for BTC; overlapping articles share market shocks.

### event_tests.csv (342 rows)

Hourly reactions are tested on event-day means, so multiple articles on one day form one cluster. BMP-style CAR is estimation-error standardized and day clustered. The −24h placebo omits [0,24], whose inclusive endpoint would overlap T0.

### event_asymmetry.csv (24 rows)

Negative-minus-positive compares same-day FinBERT and LM terciles on days where both occur. Its paired day test asks whether bad-news reaction differs from good-news reaction.

### event_timing_pairs.csv (38 rows)

The same GDELT article is aligned once to published time and once to first-seen time. Pairwise CAR changes quantify timestamp sensitivity without changing the article sample.

### event_timing.csv (3 rows)

A changed significance flag shows the timing choice can alter a nominal conclusion. This small audited subset cannot calibrate the full corpus.

### event_coverage.csv (1 rows)

Article count, scored count, usable event days and training-only tercile cutoffs limit the scope of hourly inference.

### coverage.csv (5 rows)

Coverage distinguishes collected-index news days, FinBERT-scored days and complete model rows; it does not prove absence of real-world news. Sparse dates can select an unrepresentative sample.

## Figures

- sentiment_btc.svg
- oos_loss.svg
- quantile_coefficients.svg
- shap_btc.svg

## Preliminary RQ1–RQ5

RQ1: predictive coefficients cannot rank sentiment accuracy without independent labeled validation.
RQ2: use mean Wald and tail slopes together; quantile serial inference remains a limitation.
RQ3: compare text against raw attention and momentum before attributing value to narrative composition.
RQ4: Granger establishes predictive direction only, conditional on stationarity and contiguous coverage.
RQ5: paired losses, corrected inference and economic-value tests assess incremental value; never choose models on test.

These are partial real-data associations.
Regression samples contain 673–1073 observations; minimum residual degrees of freedom=644. Tiny samples and many parameters make all significance findings exploratory.
RQ1: BTC h=1 FinBERT return slope 0.00327939, Holm p=1; identified=True; this does not validate sentiment-label accuracy.
RQ3: 0/945 estimable hard-narrative coefficients survive table-family Holm at 5%; evaluate against momentum and raw attention.
RQ2: BTC h=1 mean RV slopes negative=-0.00125623, positive=-0.00108407; equality Holm p=1.
RQ2 tail tau=0.1: negative=-0.000197448, positive=1.64827e-05; converged=True, serial inference not corrected.
RQ2 tail tau=0.5: negative=-0.000409451, positive=-0.000110817; converged=True, serial inference not corrected.
RQ2 tail tau=0.9: negative=-0.00126666, positive=-0.0010949; converged=True, serial inference not corrected.
RQ4 BTC sent_finbert predicts ret: lag=7, Holm p=1; predictive direction only.
RQ4 BTC ret predicts sent_finbert: lag=7, Holm p=4.595e-45; predictive direction only.
RQ5 BTC EN: RMSE market=0.0241618, attention=0.0241618, text=0.0241599; CT R²=-0.0004886, DM Holm p=1, CW Holm p=1 (CW exploratory).
RQ5 BTC LGBM: RMSE market=0.0244134, attention=0.0244508, text=0.0243005; CT R²=-0.01216, DM Holm p=1, CW Holm p=1 (CW exploratory).
RQ5 BTC XGB: RMSE market=0.0243238, attention=0.0242997, text=0.0244231; CT R²=-0.02241, DM Holm p=1, CW Holm p=1 (CW exploratory).

## Methods sources

- Clark & West (2007): https://users.ssc.wisc.edu/~cengel/IMF/ClarkWest2007.pdf
- DM-HLN reference arithmetic: https://github.com/johntwk/Diebold-Mariano-Test/blob/master/dm_test.py
- Giacomini & White (2006): https://doi.org/10.1111/j.1468-0262.2006.00718.x
- Hansen, Lunde & Nason (2011): https://www.kevinsheppard.com/files/teaching/mfe/advanced-econometrics/Hansen_Lunde_Nason.pdf

event_coverage 1 rows

,canonical_en_articles,article_asset_rows,scored_finbert_articles,usable_event_rows,usable_event_days,gdelt_event_rows,sec_event_rows,gdelt_article_days,sec_article_days,first_event,last_event,timing_audited_articles,finbert_train_cut_low,finbert_train_cut_high
0,142646,150160,140593,150160,1363,148066,2094,1352,503,2023-01-01 02:00:00+00:00,2026-10-01 00:00:00+00:00,36,-0.009302,0.158464

event_tests 342 rows

,grouping,group,window,metric,n_events,n_days,mean,median,t,p_t,bmp_t,p_bmp,p_wilcoxon,p_t_holm,p_bmp_holm,p_wilcoxon_holm
0,all,all,"[0,1]",car,150123,1363,-0.000036,-0.000052,-0.579330,0.562462,-0.108229,0.913830,0.320324,1.000000,1.0,1.000000
1,all,all,"[0,1]",absret,150123,1363,0.000348,0.000031,3.610496,0.000317,NaN,NaN,0.328874,0.081076,NaN,1.000000
2,all,all,"[0,1]",volume,150123,1363,0.059221,0.113224,4.305738,0.000018,NaN,NaN,0.000001,0.005029,NaN,0.000329
3,all,all,"[0,1]",placebo_car,150108,1363,0.000019,-0.000032,0.295407,0.767728,NaN,NaN,0.906233,1.000000,NaN,1.000000
4,all,all,"[0,4]",car,150104,1363,-0.000068,-0.000126,-0.508398,0.611257,-0.081050,0.935414,0.372339,1.000000,1.0,1.000000
5,all,all,"[0,4]",absret,150104,1363,0.000545,-0.000255,2.397431,0.016645,NaN,NaN,0.683676,1.000000,NaN,1.000000
6,all,all,"[0,4]",volume,150104,1363,0.033115,0.075980,2.486140,0.013033,NaN,NaN,0.002744,1.000000,NaN,0.754727
7,all,all,"[0,4]",placebo_car,150085,1363,0.000004,0.000056,0.030343,0.975798,NaN,NaN,0.739129,1.000000,NaN,1.000000
8,all,all,"[0,24]",car,149897,1363,-0.000306,-0.000084,-0.613657,0.539544,-0.065232,0.947999,0.308444,1.000000,1.0,1.000000
9,all,all,"[0,24]",absret,149897,1363,0.000449,-0.002177,0.446714,0.655153,NaN,NaN,0.028439,1.000000,NaN,1.000000

event_asymmetry 24 rows

,tone,window,metric,n_days,negative_mean,positive_mean,negative_minus_positive,p_t,p_wilcoxon,p_t_holm,p_wilcoxon_holm
0,finbert_tercile,"[0,1]",car,1352,0.000039,-0.000081,0.000121,2.817345e-02,4.426128e-03,1.972141e-01,5.753967e-02
1,finbert_tercile,"[0,1]",absret,1352,0.000298,0.000459,-0.000161,1.008291e-03,1.136674e-02,1.310778e-02,1.364009e-01
2,finbert_tercile,"[0,1]",volume,1352,0.041943,0.072700,-0.030757,9.529383e-11,1.987734e-13,2.001170e-09,4.373015e-12
3,finbert_tercile,"[0,4]",car,1352,-0.000020,-0.000159,0.000139,9.335654e-02,4.774451e-02,4.307645e-01,3.450627e-01
4,finbert_tercile,"[0,4]",absret,1352,0.000474,0.000714,-0.000239,4.921497e-03,5.743804e-02,5.413647e-02,3.450627e-01
5,finbert_tercile,"[0,4]",volume,1352,0.022285,0.050545,-0.028259,4.155174e-14,1.171517e-15,9.972419e-13,2.811640e-14
6,finbert_tercile,"[0,24]",car,1351,-0.000153,-0.000637,0.000485,4.102490e-03,1.885988e-02,4.922987e-02,2.074587e-01
7,finbert_tercile,"[0,24]",absret,1351,0.000408,0.000729,-0.000321,1.495658e-01,8.889899e-01,4.307645e-01,1.000000e+00
8,finbert_tercile,"[0,24]",volume,1351,0.002555,0.011956,-0.009401,5.184523e-06,1.082941e-04,8.813688e-05,1.841000e-03
9,finbert_tercile,"[-4,0]",car,1352,0.000182,-0.000225,0.000407,5.499725e-07,1.142594e-06,1.044948e-05,2.056669e-05

event_timing 3 rows

,window,n_pairs,n_days,n_unique_articles,mean_car_published,mean_car_seen,mean_published_minus_seen,p_paired_t,p_paired_wilcoxon,p_public,p_seen,significance_changed,p_paired_t_holm,p_paired_wilcoxon_holm,p_public_holm,p_seen_holm,significance_changed_holm
0,0_1,38,31,36,-0.000078,-0.001269,0.001191,0.362440,0.542198,0.950745,0.099590,False,0.724881,1.00000,0.950745,0.199181,False
1,0_4,38,31,36,-0.002471,-0.001988,-0.000483,0.820783,0.915394,0.143801,0.221002,False,0.820783,1.00000,0.431404,0.221002,False
2,0_24,38,31,36,-0.005025,-0.008663,0.003638,0.120842,0.163340,0.204898,0.025924,True,0.362525,0.49002,0.431404,0.077773,False

# Kết quả thật, bộ tin đang thu

Bằng chứng dưới đây chỉ áp dụng cho dữ liệu đã thu. Tin cùng ngày được gom theo ngày khi kiểm định sự kiện.

Coverage: corpus chung có 1352/1369 ngày có tin (98.76%); riêng BTC có 1351 ngày tin gắn mã (98.69%), 1 ngày mô hình dùng corpus chung; từ 2023-01-01 00:00:00+00:00 đến 2026-09-30 00:00:00+00:00. Core spec dùng 1344 ngày BTC, train/valid/test=890/182/272.

Sự kiện giờ: 142646 tin canonical tiếng Anh, 150160 cặp tin–asset trên 1363 ngày; 140593 tin có FinBERT. Mẫu 2023-01-01 02:00:00+00:00 đến 2026-10-01 00:00:00+00:00.

Bản documents hiện phủ 1352 ngày GKG và 503 ngày SEC; text_daily có thể chưa được build lại trên cùng ảnh chụp dữ liệu.

Phản ứng chung [0,4]h car: -0.006788 %, 1363 ngày, p t Holm=1.
Phản ứng chung [0,4]h absret: 0.05448 %, 1363 ngày, p t Holm=1.
Phản ứng chung [0,4]h volume: 0.03311 log điểm, 1363 ngày, p t Holm=1.
Abnormal volume là chênh log(1+USD volume) so với 144 giờ ước lượng trước tin; abnormal |return| là chênh tổng độ lớn lợi suất log.

## RQ1: FinBERT và từ điển

Đã có: hệ số BTC h=1 sent_lm=-0.0004216, Holm p=1 (n=1073); sent_hv=0.006507, Holm p=1 (n=1073); sent_finbert=0.003279, Holm p=1 (n=1073).
Chưa đủ: cần nhãn kiểm định độc lập và mẫu tin dày hơn để xếp hạng độ chính xác.
Nghĩa kinh tế: chênh hệ số dự báo không chứng minh FinBERT đọc tin đúng hơn từ điển.

## RQ2: tin xấu và tin tốt

Đã có: CAR [0,4]h FinBERT xấu trừ tốt = 0.01392 điểm %, 1352 ngày ghép cặp, p t=0.09336, Holm=0.4308; xem event_asymmetry.csv.
Biến động tuyệt đối [0,1]h xấu trừ tốt = -0.01615 điểm %, Holm t=0.01311, Holm Wilcoxon=0.1364; hai kiểm định chưa đồng thuận.
Chưa đủ: nhiều giờ có tin chồng lấp; Wald và phân vị theo ngày vẫn phụ thuộc coverage thưa.
Nghĩa kinh tế: CAR khác nhau là phản ứng giá có điều kiện, chưa xác định tác động nhân quả của sắc thái tin.

## RQ3: narrative

Đã có: regulation CAR [0,4]h = -0.004823%, 1333 ngày, p t=0.788, Holm=1.
Đã có: security_hacks CAR [0,4]h = -0.01075%, 1350 ngày, p t=0.5336, Holm=1.
Đã có: etf_institutional CAR [0,4]h = -0.01675%, 1352 ngày, p t=0.2452, Holm=1.
Chưa đủ: cần hiệu chỉnh nhiều kiểm định và kiểm soát tin trùng giờ để so thứ hạng narrative.
Nghĩa kinh tế: nhóm có CAR lớn hơn chỉ là liên hệ trong mẫu tin đã thu.

## RQ4: tin dẫn giá hay giá đi trước tin

Đã có: CAR trước tin nghiêm ngặt [-4,-2]h = -0.001552%, 1363 ngày, p t=0.8625, Holm=1. [-4,0]h có cả nến T0 nên không thuần trước tin.
Độ nhạy giờ [0,1]: 36 tin, 38 cặp tin–asset trên 31 ngày, CAR published=-0.007833%, seen=-0.1269%, p published/seen=0.9507/0.09959, đổi kết luận p<0,05=False, sau Holm=False; kiểm định chênh lệch ghép cặp Holm p=0.7249.
Độ nhạy giờ [0,4]: 36 tin, 38 cặp tin–asset trên 31 ngày, CAR published=-0.2471%, seen=-0.1988%, p published/seen=0.1438/0.221, đổi kết luận p<0,05=False, sau Holm=False; kiểm định chênh lệch ghép cặp Holm p=0.8208.
Độ nhạy giờ [0,24]: 36 tin, 38 cặp tin–asset trên 31 ngày, CAR published=-0.5025%, seen=-0.8663%, p published/seen=0.2049/0.02592, đổi kết luận p<0,05=True, sau Holm=False; kiểm định chênh lệch ghép cặp Holm p=0.3625.
Chưa đủ: 20 kiểm định Granger dùng được; VAR chỉ chạy trên đoạn ngày liên tục ≥30.
Nghĩa kinh tế: CAR trước T0 gợi ý giá đã phản ánh thông tin sớm hoặc sai số giờ công bố; không chứng minh rò rỉ.

## RQ5: dự báo ngoài mẫu

Đã có: 58284 hàng dự báo ngoài mẫu; 272 hàng BTC EN/text RV h=1 đúng schema dashboard/export.py.
As-of 2026-09-29 00:00:00+00:00: RV dự báo=0.0004627, 270 sai số quá khứ đã biết; fan chart đủ ngưỡng 30.
EN/text BTC RV h=1: R² CT=0.2073, RMSE=0.0005552; DM Holm p=1.
Chưa đủ: ngày test có tin rời rạc; DM/GW/MCS cần đoạn liên tục. Dải fan theo sai số có thể xuống dưới RV=0.
Nghĩa kinh tế: dự báo thật có thể xuất cho dashboard; lợi ích của text chỉ đáng tin nếu kiểm định ghép cặp có đủ đoạn liên tục.

Giới hạn thời điểm: GDELT seendate trễ tuyệt đối trung vị 141.5 phút trong 42 cặp audit.
GDELT đang thu tiếp; các p-value chưa giải quyết lựa chọn mẫu tin và nhiều sự kiện trùng ngày.

## Interpretation

Read `outputs/tables/real/RESULTS.md` for RQ1?RQ5 and `README.md` for coverage and each table. Hourly events cluster by day. The 24-hour placebo is omitted where a ?24h shift would overlap T0. Synthetic findings validate code only; strategy plots are economic-value tests.